In [1]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pylab as plt

In [3]:
data=pd.read_csv('Melbourne_housing_extra_data.csv')
# data=pd.read_csv('Melbourne_housing_extra_data.csv',dayfirst=True,parse_dates=True,index_col='Date')
data.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St    2.0    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St    2.0    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St    2.0    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St    3.0    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St    3.0    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode Bedroom2 Bathroom Car Landsize BuildingArea  \
0  3/09/2016       2.5    3067.0        2        1   1      126          NaN   
1  3/12/2016       2.5    3067.0        2        1   1      202          NaN   
2  4/02/2016       2.5    3067.0        2        1   0      156           79   
3  4/02/2016       2.5    3067.0        3        2   1        0          NaN   
4  4/03/2017       2.5    3067.0        3        2   0      134          150   

  YearBuilt CouncilArea Lattitude Longtitude  
0       NaN       Yarra  -37.8014   144.9958  
1       NaN       Yarra  -37.7996   144.9984  
2      1900       Yarra  -37.8079   144.9934  
3       NaN       Yarra  -37.8114   145.0116  
4      1900       Yarra  -37.8093   144.9944

In [4]:
# data.Landsize.astype('int')
data.dtypes


Suburb           object
Address          object
Rooms           float64
Type             object
Price           float64
Method           object
SellerG          object
Date             object
Distance        float64
Postcode        float64
Bedroom2         object
Bathroom         object
Car              object
Landsize         object
BuildingArea     object
YearBuilt        object
CouncilArea      object
Lattitude        object
Longtitude       object
dtype: object

In [88]:
test=data.head(100)

In [3]:
def val_counts(var):
    print(data[var].value_counts())
    print(data[var].nunique())

In [4]:
val_counts('Suburb')
val_counts('Rooms')
val_counts('Type')
val_counts('Method') #can ignore
val_counts('SellerG')#can ignore
# val_counts('year')
# val_counts('month') # month 3-8 more sales
val_counts('Postcode')

Reservoir             444
Bentleigh East        314
Richmond              301
Glen Iris             266
Preston               263
Kew                   251
Brighton              248
South Yarra           242
St Kilda              235
Brunswick             228
Coburg                226
Camberwell            226
Brighton East         226
Balwyn North          224
Essendon              222
Hawthorn              216
Glenroy               213
Malvern East          212
Northcote             210
Port Melbourne        204
Pascoe Vale           193
Prahran               187
Balwyn                180
Yarraville            175
Bentleigh             170
Thornbury             164
Toorak                164
Carnegie              161
Hawthorn East         161
Hampton               157
                     ... 
Albion                 33
Spotswood              31
Essendon West          30
South Kingsville       29
East Melbourne         29
Ivanhoe East           29
Cremorne               28
Gowanbrae   

In [19]:
data.groupby('Postcode')['Price'].mean().round().astype(int)

Postcode
3000.0     701237
3002.0    1390227
3003.0     958640
3006.0     634458
3008.0     875000
3011.0     773547
3012.0     739548
3013.0     945365
3015.0     979722
3016.0    1194479
3018.0     855139
3019.0     645379
3020.0     625838
3021.0     563024
3025.0     755567
3031.0     797362
3032.0     916211
3033.0     777125
3034.0     832062
3039.0    1116106
3040.0    1058348
3041.0    1067759
3042.0     782726
3043.0     660180
3044.0     744087
3046.0     660247
3047.0     485114
3051.0     846656
3052.0    1364958
3053.0    1049613
           ...   
3126.0    2351400
3127.0    1476780
3128.0    1195681
3141.0    1026034
3142.0    1699373
3143.0    1451671
3144.0    1874346
3145.0    1386849
3146.0    1587807
3147.0    1377830
3148.0    1003033
3161.0    1009167
3162.0    1084348
3163.0     909937
3165.0    1056442
3166.0    1052433
3167.0     960679
3181.0    1011799
3182.0     852634
3183.0     714190
3184.0     931183
3185.0    1148307
3186.0    1902363
3187.0    1579980
3

In [6]:
data.groupby('Postcode')['Price'].apply(lambda x:x.count())

Postcode
3000.0     93
3002.0     22
3003.0     25
3006.0     36
3008.0      5
3011.0    171
3012.0    213
3013.0    139
3015.0    177
3016.0    117
3018.0     66
3019.0     48
3020.0    309
3021.0     21
3025.0     82
3031.0    166
3032.0    233
3033.0    110
3034.0     80
3039.0    129
3040.0    246
3041.0    106
3042.0    168
3043.0     25
3044.0    160
3046.0    301
3047.0     22
3051.0     59
3052.0     33
3053.0     43
         ... 
3126.0     45
3127.0    148
3128.0     52
3141.0    187
3142.0    108
3143.0     82
3144.0     68
3145.0    138
3146.0    167
3147.0    122
3148.0     45
3161.0     36
3162.0     56
3163.0    244
3165.0    274
3166.0     82
3167.0     64
3181.0    158
3182.0    192
3183.0     21
3184.0    109
3185.0     70
3186.0    177
3187.0    152
3188.0    166
3189.0     63
3204.0    223
3205.0     73
3206.0     81
3207.0    144
Name: Price, dtype: int64

In [7]:
data.groupby('Postcode')['Price'].apply(lambda x:x.isnull().sum())
# data.groupby('Postcode')['Price'].isnull().sum()

Postcode
3000.0     34
3002.0      7
3003.0     11
3006.0     11
3008.0      5
3011.0     33
3012.0     48
3013.0     36
3015.0     32
3016.0     23
3018.0      4
3019.0      7
3020.0     31
3021.0      4
3025.0     12
3031.0     18
3032.0     38
3033.0     13
3034.0      8
3039.0     23
3040.0     48
3041.0     17
3042.0      7
3043.0      2
3044.0     33
3046.0     53
3047.0      2
3051.0     17
3052.0      4
3053.0      6
         ... 
3126.0     28
3127.0     66
3128.0     19
3141.0     55
3142.0     56
3143.0     57
3144.0     75
3145.0     86
3146.0     99
3147.0     50
3148.0     19
3161.0      8
3162.0     22
3163.0     41
3165.0     40
3166.0     23
3167.0     10
3181.0    105
3182.0     43
3183.0      5
3184.0     47
3185.0     26
3186.0     71
3187.0     74
3188.0     51
3189.0      8
3204.0     34
3205.0     19
3206.0     34
3207.0     60
Name: Price, dtype: int64

In [5]:
data['Price']=data['Price'].groupby(data['Postcode']).apply(lambda x :x.fillna(round(x.mean())))

In [6]:
data

Suburb                 Address  Rooms Type      Price Method  \
0          Abbotsford           68 Studley St    2.0    h  1027385.0     SS   
1          Abbotsford            85 Turner St    2.0    h  1480000.0      S   
2          Abbotsford         25 Bloomburg St    2.0    h  1035000.0      S   
3          Abbotsford      18/659 Victoria St    3.0    u  1027385.0     VB   
4          Abbotsford            5 Charles St    3.0    h  1465000.0     SP   
5          Abbotsford        40 Federation La    3.0    h   850000.0     PI   
6          Abbotsford             55a Park St    4.0    h  1600000.0     VB   
7          Abbotsford            16 Maugie St    4.0    h  1027385.0     SN   
8          Abbotsford            53 Turner St    2.0    h  1027385.0      S   
9          Abbotsford            99 Turner St    2.0    h  1027385.0      S   
10         Abbotsford          129 Charles St    2.0    h   941000.0      S   
11         Abbotsford            124 Yarra St    3.0    h  1876000.0      S   
12         Abbotsford     121/56 Nicholson St    2.0    u  1027385.0     PI   
13         Abbotsford           17 Raphael St    4.0    h  1027385.0      W   
14         Abbotsford           98 Charles St    2.0    h  1636000.0      S   
15         Abbotsford        217 Langridge St    3.0    h  1000000.0      S   
16         Abbotsford         18a Mollison St    2.0    t   745000.0      S   
17         Abbotsford      6/241 Nicholson St    1.0    u   300000.0      S   
18         Abbotsford           10 Valiant St    2.0    h  1097000.0      S   
19         Abbotsford     403/609 Victoria St    2.0    u   542000.0      S   
20         Abbotsford               2 Rich St    2.0    h  1027385.0     SP   
21         Abbotsford       25/84 Trenerry Cr    2.0    u   760000.0     SP   
22         Abbotsford       106/119 Turner St    1.0    u   481000.0     SP   
23         Abbotsford      411/8 Grosvenor St    2.0    u   700000.0     VB   
24         Abbotsford         40 Nicholson St    3.0    h  1350000.0     VB   
25         Abbotsford     123/56 Nicholson St    2.0    u   750000.0      S   
26         Abbotsford              22 Park St    4.0    h  1985000.0      S   
27         Abbotsford       13/84 Trenerry Cr    1.0    u   500000.0      S   
28         Abbotsford           45 William St    2.0    h  1172500.0      S   
29         Abbotsford      7/20 Abbotsford St    1.0    u   441000.0     SP   
...               ...                     ...    ...  ...        ...    ...   
14212         Windsor          2/6 The Avenue    2.0    u   690000.0      S   
14213         Windsor      3/217 Dandenong Rd    2.0    u   854000.0     SP   
14214         Windsor             108 Peel St    1.0    h   900000.0     VB   
14215         Windsor           7/113 Punt Rd    1.0    u   350000.0     SP   
14216       Yallambie         24 Bimbadeen Cr    4.0    h   779108.0     PI   
14217       Yallambie          19 Goulburn Gr    4.0    h   955000.0     PI   
14218       Yallambie          57 Tarcoola Dr    3.0    h   721500.0      S   
14219       Yallambie           14 Borlase St    5.0    h  1060000.0      S   
14220       Yallambie              8 Lowan Av    4.0    h   780250.0     SP   
14221       Yallambie          7 Marigolds Rd    3.0    h   984000.0      S   
14222       Balaclava       4/247 Inkerman St    2.0    u   450000.0     SP   
14223       Balaclava         5/171 Hotham St    2.0    u   490000.0     VB   
14224       Balaclava          2/31 Orange Gr    1.0    u   440000.0      S   
14225   Essendon West            2 Diamond St    3.0    h  1406000.0      S   
14226   Essendon West             7 Garnet St    3.0    h  1305000.0      S   
14227       Kingsbury          1/37 Clunes St    3.0    u   488000.0      S   
14228         Kooyong            26 Monaro Rd    5.0    h  1874346.0     PI   
14229  West Melbourne        36 Abbotsford St    2.0    h   958640.0     SN   
14230  West Melbourne         218 Adderley St    3.0    h  175000

In [104]:
pd.crosstab(data.Date,data.Rooms)

Rooms       1.0   2.0   3.0   4.0   5.0   99.0
Date                                          
10/09/2016    20   102   136    91    27     6
10/12/2016    32   161   209    94    26     6
11/02/2017    12    54    46    17     2     1
11/03/2017     4    16    23    17     5     0
12/06/2016     4    22    32     8    10     0
12/11/2016    25   143   182    98    22     5
13/05/2017    20   123   170    84    22     3
13/08/2016    14    85    84    40     6     3
14/05/2016    16   116   122    48    16     4
15/10/2016    26   143   187    85    22     3
16/04/2016    12    93   149    59    15     5
16/07/2016    20    69    89    34     5     2
17/09/2016    16   104   166    66    23     2
18/03/2017    31   159   194   101    21     7
18/06/2016    20   121   180    87    30     3
19/11/2016    22   133   163    91    18     4
20/05/2017    19   119   204    88    25     2
22/04/2017    14    81    86    38     4     3
22/05/2016    22    98   126    69    17     4
22/08/2016    21    80   123    57     8     4
23/04/2016     8    51    79    25     6     0
24/09/2016    22   133   153    59     6     4
25/02/2017    31   145   235   120    19     5
26/07/2016     8    65    85    38     1     2
27/06/2016    20   103   148    67    17     2
27/11/2016    31   141   238   135    24     6
28/01/2016     0     1     1     1     0     0
28/05/2016    21   106   194    98    32     3
28/08/2016    24   103   168    74    19     2
29/04/2017    24   106   138    56    16     1
3/09/2016     15    96   138    68    14     2
3/12/2016     32   114   204    98    17     7
30/07/2016    21    87   102    47    11     3
4/02/2016      4    15    19     4     1     1
4/03/2017     26   148   202   115    31    10
4/06/2016     17   108   153    70    13     7
6/05/2017     12    76   103    35     9     1
6/08/2016     13    90    89    47    12     7
7/05/2016     23   114   167    88    22     5
7/11/2016     19   111   120    45    10     1
8/04/2017     38   132   205    65     9     2
8/10/2016     22   130   151    67    14     2

In [8]:
data.loc[data.Rooms > 5,'Rooms']=99

In [9]:
pd.crosstab(data.Rooms,data.Type)


Type      h    t     u
Rooms                 
1.0      48    7   746
2.0    1479  458  2260
3.0    4428  839   533
4.0    2424  259    24
5.0     619   10     0
99.0     82    1     5

In [10]:
test.Rooms.unique()

NameError: name 'test' is not defined

In [57]:
def room():
    for i in test['Rooms']:
        if i > 3:
            i=99
            return(i)

In [153]:
test.loc[test.Rooms >2,'Rooms']=99
test.loc[test.Landsize=='Unavailable','Landsize']=0
test.loc[test.Landsize==' ','Landsize']=0
test

Suburb              Address  Rooms Type      Price Method  \
0     Abbotsford        68 Studley St    2.0    h        NaN     SS   
1     Abbotsford         85 Turner St    2.0    h  1480000.0      S   
2     Abbotsford      25 Bloomburg St    2.0    h  1035000.0      S   
3     Abbotsford   18/659 Victoria St   99.0    u        NaN     VB   
4     Abbotsford         5 Charles St   99.0    h  1465000.0     SP   
5     Abbotsford     40 Federation La   99.0    h   850000.0     PI   
6     Abbotsford          55a Park St   99.0    h  1600000.0     VB   
7     Abbotsford         16 Maugie St   99.0    h        NaN     SN   
8     Abbotsford         53 Turner St    2.0    h        NaN      S   
9     Abbotsford         99 Turner St    2.0    h        NaN      S   
10    Abbotsford       129 Charles St    2.0    h   941000.0      S   
11    Abbotsford         124 Yarra St   99.0    h  1876000.0      S   
12    Abbotsford  121/56 Nicholson St    2.0    u        NaN     PI   
13    Abbotsford        17 Raphael St   99.0    h        NaN      W   
14    Abbotsford        98 Charles St    2.0    h  1636000.0      S   
15    Abbotsford     217 Langridge St   99.0    h  1000000.0      S   
16    Abbotsford      18a Mollison St    2.0    t   745000.0      S   
17    Abbotsford   6/241 Nicholson St    1.0    u   300000.0      S   
18    Abbotsford        10 Valiant St    2.0    h  1097000.0      S   
19    Abbotsford  403/609 Victoria St    2.0    u   542000.0      S   
20    Abbotsford            2 Rich St    2.0    h        NaN     SP   
21    Abbotsford    25/84 Trenerry Cr    2.0    u   760000.0     SP   
22    Abbotsford    106/119 Turner St    1.0    u   481000.0     SP   
23    Abbotsford   411/8 Grosvenor St    2.0    u   700000.0     VB   
24    Abbotsford      40 Nicholson St   99.0    h  1350000.0     VB   
25    Abbotsford  123/56 Nicholson St    2.0    u   750000.0      S   
26    Abbotsford           22 Park St   99.0    h  1985000.0      S   
27    Abbotsford    13/84 Trenerry Cr    1.0    u   500000.0      S   
28    Abbotsford        45 William St    2.0    h  1172500.0      S   
29    Abbotsford   7/20 Abbotsford St    1.0    u   441000.0     SP   
..           ...                  ...    ...  ...        ...    ...   
70  Airport West           23 Hart St    2.0    h   603000.0      S   
71  Airport West       1/80 Hawker St   99.0    t   700000.0      S   
72  Airport West     1/37 Hillside Gr   99.0    h   600000.0      S   
73  Airport West     2/49 McIntosh St    2.0    u   500000.0     VB   
74  Airport West          4/9 West Ct    2.0    t   420000.0     VB   
75  Airport West         1/36 York St   99.0    t   500000.0     VB   
76  Airport West          33 Bowes Av   99.0    h  1035000.0      S   
77  Airport West          89 Bowes Av   99.0    h   960000.0      S   
78  Airport West       45 Laurence Av   99.0    h   960000.0      S   
79  Airport West       54 Marshall Rd   99.0    h   720000.0      S   
80  Airport West        36 Roberts Rd   99.0    h   785000.0      S   
81  Airport West     11 Harrington Rd   99.0    h   725000.0     SP   
82  Airport West       2/252 Parer Rd    2.0    t   450000.0      S   
83  Airport West         3/19 Hart St    2.0    u   515000.0      S   
84  Airport West       81a Roberts Rd   99.0    h   680000.0     VB   
85  Airport West   2/62 Clydesdale Rd    2.0    u   530000.0      S   
86  Airport West          3 Deidre Ct   99.0    h   895000.0     PI   
87  Airport West      3/24 Elstone Av   99.0    u   600000.0     VB   
88  Airport West          13 Etzel St   99.0    h   805000.0      S   
89  Airport West         37a North St   99.0    t   760000.0     PI   
90  Airport West      1/43 Cameron St   99.0    u   752000.0      S   
91  Airport West        1/69 Bowes Av   99.0    u   580000.0     VB   
92  Airport West       2/9 El Reno Cr   99.0    h   725000.0     PI   
93  Airport West       92 McNamara Av   99.0    h   758000.0      S   
94  Airport West      145a Victory

In [11]:
data.Distance.mean()

8.621635494304728

In [222]:
data.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [112]:

import folium
mapit = None
latlon = [ (51.249443914705175, -0.13878830247011467), (51.249443914705175, -0.13878830247011467), (51.249768239976866, -2.8610415615063034)]
for coord in latlon:
    mapit = folium.Map( location=[ coord[0], coord[1] ] )

mapit.save( 'map.html')

In [113]:
data.Price.isnull().sum()

3173

In [114]:
data.BuildingArea.isnull().sum()

7166

In [12]:
data.count()

Suburb          14242
Address         14232
Rooms           14222
Type            14222
Price           14222
Method          14222
SellerG         14222
Date            14222
Distance        14222
Postcode        14222
Bedroom2        11222
Bathroom        11222
Car             11222
Landsize        11213
BuildingArea     7076
YearBuilt        7852
CouncilArea     11213
Lattitude       11307
Longtitude      11307
dtype: int64

In [13]:
data=data[data['Suburb']!='    RE']
data.Suburb.unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington', 'Altona',
       'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton', 'Ashwood',
       'Avondale Heights', 'Balaclava', 'Balwyn', 'Balwyn North',
       'Bentleigh', 'Bentleigh East', 'Box Hill', 'Braybrook', 'Brighton',
       'Brighton East', 'Brunswick', 'Brunswick West', 'Bulleen',
       'Burwood', 'Camberwell', 'Canterbury', 'Carlton North', 'Carnegie',
       'Caulfield', 'Caulfield North', 'Caulfield South', 'Chadstone',
       'Clifton Hill', 'Coburg', 'Coburg North', 'Collingwood',
       'Doncaster', 'Eaglemont', 'Elsternwick', 'Elwood', 'Essendon',
       'Essendon North', 'Fairfield', 'Fitzroy', 'Fitzroy North',
       'Flemington', 'Footscray', 'Glen Iris', 'Glenroy', 'Gowanbrae',
       'Hadfield', 'Hampton', 'Hampton East', 'Hawthorn',
       'Heidelberg Heights', 'Heidelberg West', 'Hughesdale', 'Ivanhoe',
       'Kealba', 'Keilor East', 'Kensington', 'Kew', 'Kew East', 'Kooyong',
       'Maidstone', 

In [14]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
label_enc=LabelEncoder()

In [19]:
X=data[['Rooms','Type','Method','Distance','Price']].values

In [20]:
y=data['Postcode'].values

In [21]:
X[:,1] =label_enc.fit_transform(X[:,1])
X[:,2] =label_enc.fit_transform(X[:,2])
onehot_enc=OneHotEncoder(categorical_features=[1,2])
X=onehot_enc.fit_transform(X).toarray()

In [23]:
np.unique(X[:,2])

array([ 0.,  1.])

In [24]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.02738500e+06],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.48000000e+06],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   2.50000000e+00,   1.03500000e+06],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   9.30000000e+00,   9.10000000e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.00000000e+00,   5.30000000e+00,   3.60000000e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.00000000e+00,   1.27000000e+01,   8.55139000e+05]])

In [25]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit_transform(["paris", "paris", "tokyo", "amsterdam"])

array([1, 1, 2, 0], dtype=int64)

In [26]:
y[0:]=le.fit_transform(y)

In [27]:
np.unique(y)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.])

In [28]:
y

array([ 39.,  39.,  39., ...,  71.,  16.,  10.])

In [29]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle

In [30]:
X1,y1=X,y

In [31]:
y2=shuffle(y1,random_state=1)
y3=shuffle(y1,random_state=2)

In [32]:
Y=np.vstack((y1,y2,y3)).T
Y

array([[ 39.,  82.,  93.],
       [ 39.,  12.,  67.],
       [ 39.,  15.,  44.],
       ..., 
       [ 71.,  73.,  16.],
       [ 16.,  10.,  63.],
       [ 10.,  41.,  41.]])